### PR TITLE
de-serialization relies loading a pickle file need allow_dangerous_deserialization=True

### PR DESCRIPTION
**Pull request by weedge**

### CODE REVIEW

**Comment by tpoisonooo** [comment]
I guess that is a version problem, see https://stackoverflow.com/questions/78120202/de-serialization-relies-loading-a-pickle-file  and https://community.dataiku.com/t5/Setup-Configuration/When-using-RAG-in-Prompt-Studio-an-error-occurs/m-p/41636 

Thanks for your contribution !

**Comment by tpoisonooo** [comment]
```bash
TypeError: __init__() got an unexpected keyword argument 'allow_dangerous_deserialization' 
```

Let me try to fix it,  qaq~

**Comment by tpoisonooo** [comment]
This parameter requires  langchain>=0.1.12, see  https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.faiss.FAISS.html

so this PR merged here https://github.com/InternLM/HuixiangDou/pull/154

cc @weedge

**Comment by weedge** [comment]
langchain                        0.1.12

```
!pip list | grep langchain
langchain                        0.1.12
langchain-community              0.0.28
langchain-core                   0.1.32
langchain-text-splitters         0.0.1
```

**Comment by weedge** [comment]
@tpoisonooo maybe use langchain==0.1.12 ,  if langchain upgrad, maybe have same issue

**Comment by tpoisonooo** [comment]
> @tpoisonooo maybe use langchain==0.1.12 , if langchain upgrad, maybe have same issue

Yes it needs `langchain>=0.1.12`,   `requirements.txt` in main branch already updated.

**Pull request merged**
